In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
file=pd.read_csv("D:\Acmegrade\Files\Social_Network_Ads.csv")
file

User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [3]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [4]:
x=file.iloc[:,1:-1].values
y=file.iloc[:,-1].values
x

array([['Male', 42, 121315],
       ['Male', 53, 67214],
       ['Female', 59, 111005],
       ...,
       ['Female', 25, 82560],
       ['Male', 55, 147667],
       ['Female', 54, 134972]], dtype=object)

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [7]:
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x

array([[1, 42, 121315],
       [1, 53, 67214],
       [0, 59, 111005],
       ...,
       [0, 25, 82560],
       [1, 55, 147667],
       [0, 54, 134972]], dtype=object)

In [9]:
ct=ColumnTransformer(transformers=[("onehot", OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

In [10]:
x

array([[0.0, 1.0, 42, 121315],
       [0.0, 1.0, 53, 67214],
       [1.0, 0.0, 59, 111005],
       ...,
       [1.0, 0.0, 25, 82560],
       [0.0, 1.0, 55, 147667],
       [1.0, 0.0, 54, 134972]], dtype=object)

In [11]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x=ss.fit_transform(x)

In [12]:
x

array([[-1.02020406,  1.02020406,  0.17951354,  0.76103154],
       [-1.02020406,  1.02020406,  1.11315372, -1.14804259],
       [ 0.98019606, -0.98019606,  1.622412  ,  0.39722026],
       ...,
       [ 0.98019606, -0.98019606, -1.26338491, -0.60652484],
       [-1.02020406,  1.02020406,  1.28290648,  1.69092048],
       [ 0.98019606, -0.98019606,  1.1980301 ,  1.24294916]])

In [13]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test= tts(x,y,test_size=0.2)

In [1]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier(n_neighbors=4)

In [27]:
knc.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [28]:
a=knc.predict(x_test)
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [29]:
final=knc.predict(x)
final

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,

In [30]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y,final)
acc

0.6825

In [33]:
lst=[]
for i in range(1,50):
    knc=KNeighborsClassifier(n_neighbors=i)
    knc.fit(x_train,y_train)
    a=knc.predict(x)
    acc=accuracy_score(y,a)
    print("Accuracy Score when i=",i,"is",acc)

Accuracy Score when i= 1 is 0.8925
Accuracy Score when i= 2 is 0.715
Accuracy Score when i= 3 is 0.7
Accuracy Score when i= 4 is 0.6825
Accuracy Score when i= 5 is 0.67
Accuracy Score when i= 6 is 0.64
Accuracy Score when i= 7 is 0.64
Accuracy Score when i= 8 is 0.635
Accuracy Score when i= 9 is 0.6625
Accuracy Score when i= 10 is 0.6425
Accuracy Score when i= 11 is 0.655
Accuracy Score when i= 12 is 0.6525
Accuracy Score when i= 13 is 0.6475
Accuracy Score when i= 14 is 0.6525
Accuracy Score when i= 15 is 0.635
Accuracy Score when i= 16 is 0.64
Accuracy Score when i= 17 is 0.6525
Accuracy Score when i= 18 is 0.6525
Accuracy Score when i= 19 is 0.64
Accuracy Score when i= 20 is 0.645
Accuracy Score when i= 21 is 0.6475
Accuracy Score when i= 22 is 0.64
Accuracy Score when i= 23 is 0.645
Accuracy Score when i= 24 is 0.6275
Accuracy Score when i= 25 is 0.625
Accuracy Score when i= 26 is 0.6325
Accuracy Score when i= 27 is 0.6175
Accuracy Score when i= 28 is 0.635
Accuracy Score when i= 2

In [35]:
df_pred=pd.DataFrame(final,columns=["Predicted Output"])
result=pd.concat([file,df_pred], axis=1)
result.to_excel("D:\Acmegrade\Outputs\KNN.xlsx")