In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
file=pd.read_csv("D:\Acmegrade\Files\Employee.csv")
file

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [46]:
x=file.iloc[:,:-1].values
y=file.iloc[:,-1].values
x

array([['Bachelors', 2017, 'Bangalore', ..., 'Male', 'No', 0],
       ['Bachelors', 2013, 'Pune', ..., 'Female', 'No', 3],
       ['Bachelors', 2014, 'New Delhi', ..., 'Female', 'No', 2],
       ...,
       ['Masters', 2018, 'New Delhi', ..., 'Male', 'No', 5],
       ['Bachelors', 2012, 'Bangalore', ..., 'Male', 'Yes', 2],
       ['Bachelors', 2015, 'Bangalore', ..., 'Male', 'Yes', 4]],
      dtype=object)

In [47]:
y

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [48]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64 
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64 
 4   Age                        4653 non-null   int64 
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64 
 8   LeaveOrNot                 4653 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 327.3+ KB


In [49]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [50]:
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])

In [51]:
x[:,2]=le.fit_transform(x[:,2])
x[:,5]=le.fit_transform(x[:,5])
x[:,6]=le.fit_transform(x[:,6])
x

array([[0, 2017, 0, ..., 1, 0, 0],
       [0, 2013, 2, ..., 0, 0, 3],
       [0, 2014, 1, ..., 0, 0, 2],
       ...,
       [1, 2018, 1, ..., 1, 0, 5],
       [0, 2012, 0, ..., 1, 1, 2],
       [0, 2015, 0, ..., 1, 1, 4]], dtype=object)

In [52]:
ct=ColumnTransformer(transformers=[("onehot",OneHotEncoder(),[0,2,5,6])],remainder="passthrough")
x=ct.fit_transform(x)

In [53]:
print(pd.DataFrame(x))

       0    1    2    3    4    5    6    7    8    9     10 11  12 13
0     1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  2017  3  34  0
1     1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  2013  1  28  3
2     1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  2014  3  38  2
3     0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  2016  3  27  5
4     0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2017  3  24  2
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ... ..  .. ..
4648  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  2013  3  26  4
4649  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  2013  2  37  2
4650  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  2018  3  27  5
4651  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  2012  3  30  2
4652  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  2015  3  33  4

[4653 rows x 14 columns]


In [54]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(3722, 14) (931, 14) (3722,) (931,)


In [55]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [56]:
gnb.fit(x_train,y_train)

GaussianNB()

In [57]:
a=gnb.predict(x)
a

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [58]:
from sklearn.metrics import accuracy_score as asc
acc=asc(y,a)
acc

0.6971846120782291

In [59]:
from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()

In [60]:
bnb.fit(x_train,y_train)

BernoulliNB()

In [61]:
b=bnb.predict(x)
b

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [62]:
acc=asc(y,b)
acc

0.7274876423812594

In [63]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(x_train,y_train)

MultinomialNB()

In [64]:
c=mnb.predict(x)
c

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [65]:
acc=asc(y,c)
acc

0.7362991618310767

# Using RF AND DT

In [85]:
lst=[]
from sklearn.metrics import accuracy_score
for i in range(50):
    a=DecisionTreeClassifier(min_samples_split=i)
    dt.fit(x_train,y_train)
    b=dt.predict(x)
    acc=accuracy_score(y,b)
    print("Accuracy Score when i=",i,"is",acc)
    lst.append(acc)
max=max(lst)
print("Highest Accuracy is at i=",lst.index(max),"of",max)
    

Accuracy Score when i= 0 is 0.9080163335482484
Accuracy Score when i= 1 is 0.9075865033311842
Accuracy Score when i= 2 is 0.90715667311412
Accuracy Score when i= 3 is 0.9078014184397163
Accuracy Score when i= 4 is 0.90715667311412
Accuracy Score when i= 5 is 0.9082312486567806
Accuracy Score when i= 6 is 0.9073715882226521
Accuracy Score when i= 7 is 0.9082312486567806
Accuracy Score when i= 8 is 0.9086610788738448
Accuracy Score when i= 9 is 0.9075865033311842
Accuracy Score when i= 10 is 0.9075865033311842
Accuracy Score when i= 11 is 0.9075865033311842
Accuracy Score when i= 12 is 0.9069417580055877
Accuracy Score when i= 13 is 0.9075865033311842
Accuracy Score when i= 14 is 0.9084461637653127
Accuracy Score when i= 15 is 0.9084461637653127
Accuracy Score when i= 16 is 0.9082312486567806
Accuracy Score when i= 17 is 0.9086610788738448
Accuracy Score when i= 18 is 0.9075865033311842
Accuracy Score when i= 19 is 0.9069417580055877
Accuracy Score when i= 20 is 0.9075865033311842
Accura

In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,r2_score as rs
from sklearn.metrics import mean_squared_error as mse
lst1=[]
for i in range(1,50):
    rf=RandomForestClassifier(n_estimators=i)
    rf.fit(x_train,y_train)
    a=rf.predict(x)
    acc2=rs(y,a)
    print("Accuracy Score when i=",i,"is",acc2)

Accuracy Score when i= 1 is 0.43418727481166086
Accuracy Score when i= 2 is 0.4322821814608584
Accuracy Score when i= 3 is 0.5265843023255816
Accuracy Score when i= 4 is 0.5161062888961678
Accuracy Score when i= 5 is 0.5542081559122176
Accuracy Score when i= 6 is 0.536109769079594
Accuracy Score when i= 7 is 0.5742116360956437
Accuracy Score when i= 8 is 0.57897436947265
Accuracy Score when i= 9 is 0.5837371028496563
Accuracy Score when i= 10 is 0.57897436947265
Accuracy Score when i= 11 is 0.5827845561742551
Accuracy Score when i= 12 is 0.57897436947265
Accuracy Score when i= 13 is 0.5856421962004588
Accuracy Score when i= 14 is 0.5961202096298723
Accuracy Score when i= 15 is 0.5932625696036686
Accuracy Score when i= 16 is 0.5913574762528662
Accuracy Score when i= 17 is 0.5942151162790699
Accuracy Score when i= 18 is 0.5961202096298723
Accuracy Score when i= 19 is 0.60183548968228
Accuracy Score when i= 20 is 0.5942151162790699
Accuracy Score when i= 21 is 0.5970727563052737
Accuracy 

In [83]:
for i in range(1,39):
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.metrics import r2_score
    knr=KNeighborsClassifier(n_neighbors=i)
    knr.fit(x_train,y_train)
    a=knr.predict(x)
    acc=r2_score(y,a)
    print(acc)

0.4818146085817231
0.33226478054372777
0.368461554208975
0.2589186865378319
0.2979731002292829
0.21510153946937471
0.21700663282017718
0.18271495250573233
0.20271843268915857
0.12841979200786147
0.15318600556829376
0.13413507206026887
0.16080637897150374
0.11889432525384902
0.14461308548968266
0.11794177857844779
0.1455656321650839
0.07602972486079307
0.10936885849983657
0.07412463150999049
0.08365009826400294
0.07507717818539172
0.0769822715361943
0.03507021781853947
0.05697879135276818
0.029354937766132072
0.04459568457255192
0.012209097608909647
0.043643137897150686
0.029354937766132072
0.03507021781853947
0.0055412708811009015
0.02649729773992826
-0.0001740091713064995
0.02363965771372456
0.002683630854897201
0.009351457582705947
-0.024940222731738793


array([0.23684211, 0.78947368, 0.31578947, ..., 0.65789474, 0.31578947,
       0.07894737])