In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
file=pd.read_csv("D:\Acmegrade\Files\Employee.csv")
file

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [6]:
x=file.iloc[:,:-1].values
y=file.iloc[:,-1].values
x

array([['Bachelors', 2017, 'Bangalore', ..., 'Male', 'No', 0],
       ['Bachelors', 2013, 'Pune', ..., 'Female', 'No', 3],
       ['Bachelors', 2014, 'New Delhi', ..., 'Female', 'No', 2],
       ...,
       ['Masters', 2018, 'New Delhi', ..., 'Male', 'No', 5],
       ['Bachelors', 2012, 'Bangalore', ..., 'Male', 'Yes', 2],
       ['Bachelors', 2015, 'Bangalore', ..., 'Male', 'Yes', 4]],
      dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [8]:
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])

In [9]:
x[:,2]=le.fit_transform(x[:,2])
x[:,5]=le.fit_transform(x[:,5])
x[:,6]=le.fit_transform(x[:,6])
x

array([[0, 2017, 0, ..., 1, 0, 0],
       [0, 2013, 2, ..., 0, 0, 3],
       [0, 2014, 1, ..., 0, 0, 2],
       ...,
       [1, 2018, 1, ..., 1, 0, 5],
       [0, 2012, 0, ..., 1, 1, 2],
       [0, 2015, 0, ..., 1, 1, 4]], dtype=object)

In [10]:
ct=ColumnTransformer(transformers=[("onehot",OneHotEncoder(),[0,2,5,6])],remainder="passthrough")
x=ct.fit_transform(x)

In [11]:
print(pd.DataFrame(x))

       0    1    2    3    4    5    6    7    8    9     10 11  12 13
0     1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  2017  3  34  0
1     1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  2013  1  28  3
2     1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  2014  3  38  2
3     0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  2016  3  27  5
4     0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2017  3  24  2
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ... ..  .. ..
4648  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  2013  3  26  4
4649  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  2013  2  37  2
4650  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  2018  3  27  5
4651  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  2012  3  30  2
4652  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  2015  3  33  4

[4653 rows x 14 columns]


In [12]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(3722, 14) (931, 14) (3722,) (931,)


In [14]:
from sklearn.svm import SVC
#4 types linear,sigmoid,rbf,poly

In [15]:
sv=SVC(kernel="linear")
sv.fit(x_train,y_train)
a=sv.predict(x)
a

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score as acs
acc1=acs(y,a)
acc1

0.7356544165054804

In [25]:
sv=SVC(kernel="sigmoid",degree=3)
sv.fit(x_train,y_train)
a=sv.predict(x)
a

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
acc1=acs(y,a)
acc1

0.6561358263485924

In [27]:
sv=SVC(kernel="rbf")
sv.fit(x_train,y_train)
a=sv.predict(x)
a

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
acc1=acs(y,a)
acc1

0.6561358263485924

In [29]:
sv=SVC(kernel="poly")
sv.fit(x_train,y_train)
a=sv.predict(x)
a

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
acc1=acs(y,a)
acc1

0.6561358263485924