In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
file=pd.read_csv("D:\Acmegrade\Files\Bank Data Dimension Reduction.csv")
file

Index  Interest  Credit  Gender  Previous  Duration Churn
0        0   17546.0       1     0.0       0.0      48.0    NO
1        1   30085.1       3     1.0       1.0      40.0   YES
2        2   16575.4       0     0.0       1.0      51.0   YES
3        3   20375.4       3     0.0       0.0      23.0   YES
4        4   50576.3       0     0.0       0.0      57.0    NO
..     ...       ...     ...     ...       ...       ...   ...
595    595   47025.0       2     0.0       1.0       NaN   YES
596    596    9672.3       0     0.0       1.0       NaN   YES
597    597   15976.3       0     0.0       1.0       NaN    NO
598    598   14711.8       0     1.0       0.0      29.0    NO
599    599   26671.6       0     1.0       1.0      38.0   YES

[600 rows x 7 columns]

In [4]:
file.isna().sum()

Index        0
Interest    68
Credit       0
Gender      21
Previous     7
Duration    70
Churn        0
dtype: int64

In [7]:
file.dtypes

Index         int64
Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object

In [16]:
file.groupby("Gender").size()

Gender
0.0    290
1.0    289
dtype: int64

In [17]:
file["Gender"]=file["Gender"].fillna(0)

In [19]:
file.isna().sum()

Index        0
Interest    68
Credit       0
Gender       0
Previous     7
Duration    70
Churn        0
dtype: int64

In [20]:
file.groupby("Previous").size()

Previous
0.0    302
1.0    291
dtype: int64

In [21]:
file["Previous"]=file["Previous"].fillna(0)
file.isna().sum()

Index        0
Interest    68
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64

In [24]:
file["Interest"].fillna(file["Interest"].mean(), inplace=True)

In [25]:
file.isna().sum()

Index        0
Interest     0
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64

In [26]:
file["Duration"].fillna(file["Duration"].mean(), inplace=True)

In [27]:
file.isna().sum()

Index       0
Interest    0
Credit      0
Gender      0
Previous    0
Duration    0
Churn       0
dtype: int64

In [28]:
file

Index  Interest  Credit  Gender  Previous   Duration Churn
0        0   17546.0       1     0.0       0.0  48.000000    NO
1        1   30085.1       3     1.0       1.0  40.000000   YES
2        2   16575.4       0     0.0       1.0  51.000000   YES
3        3   20375.4       3     0.0       0.0  23.000000   YES
4        4   50576.3       0     0.0       0.0  57.000000    NO
..     ...       ...     ...     ...       ...        ...   ...
595    595   47025.0       2     0.0       1.0  42.645283   YES
596    596    9672.3       0     0.0       1.0  42.645283   YES
597    597   15976.3       0     0.0       1.0  42.645283    NO
598    598   14711.8       0     1.0       0.0  29.000000    NO
599    599   26671.6       0     1.0       1.0  38.000000   YES

[600 rows x 7 columns]

In [31]:
print(file.dtypes)

Index         int64
Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object


In [33]:
file["Gender"]=file["Gender"].astype("category")

In [34]:
print(file.dtypes)

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous     float64
Duration     float64
Churn         object
dtype: object


In [35]:
file["Previous"]=file["Previous"].astype("category")
print(file.dtypes)

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn         object
dtype: object


In [37]:
file["Churn"]=file["Churn"].astype("category")
file["Churn"]=file["Churn"].cat.codes
print(file.dtypes)

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn           int8
dtype: object


In [38]:
file

Index  Interest  Credit Gender Previous   Duration  Churn
0        0   17546.0       1    0.0      0.0  48.000000      0
1        1   30085.1       3    1.0      1.0  40.000000      1
2        2   16575.4       0    0.0      1.0  51.000000      1
3        3   20375.4       3    0.0      0.0  23.000000      1
4        4   50576.3       0    0.0      0.0  57.000000      0
..     ...       ...     ...    ...      ...        ...    ...
595    595   47025.0       2    0.0      1.0  42.645283      1
596    596    9672.3       0    0.0      1.0  42.645283      1
597    597   15976.3       0    0.0      1.0  42.645283      0
598    598   14711.8       0    1.0      0.0  29.000000      0
599    599   26671.6       0    1.0      1.0  38.000000      1

[600 rows x 7 columns]

In [46]:
x=file.iloc[:,1:6].values
y=file.iloc[:,6].values
x

array([[1.7546000e+04, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.8000000e+01],
       [3.0085100e+04, 3.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        4.0000000e+01],
       [1.6575400e+04, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        5.1000000e+01],
       ...,
       [1.5976300e+04, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        4.2645283e+01],
       [1.4711800e+04, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        2.9000000e+01],
       [2.6671600e+04, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        3.8000000e+01]])

In [47]:
y

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,

In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
ss=StandardScaler()
x=ss.fit_transform(x)

In [50]:
x

array([[-0.83481117, -0.01104933, -0.96398156, -0.97043679,  0.3966542 ],
       [ 0.20322955,  1.88312118,  1.03736424,  1.03046381, -0.19595109],
       [-0.91516162, -0.95813458, -0.96398156,  1.03046381,  0.61888119],
       ...,
       [-0.9647577 , -0.95813458, -0.96398156,  1.03046381,  0.        ],
       [-1.06943845, -0.95813458,  1.03736424, -0.97043679, -1.01078337],
       [-0.07935469, -0.95813458,  1.03736424,  1.03046381, -0.34410241]])

In [61]:
from sklearn.decomposition import PCA
pca=PCA(n_components=None)
pca.fit(x)

PCA()

In [62]:
pca1=pca.transform(x)
print(pd.DataFrame(pca1))

            0         1         2         3         4
0   -0.387779 -1.261345  0.564220  0.218706 -0.786024
1    0.261090  2.124416  0.931661  0.535814  0.165607
2    0.009422 -0.424485 -0.079987 -1.681341 -1.056452
3   -1.328791 -0.270103  2.207657  0.866583  0.657428
4    1.866791 -1.791676 -0.564974  0.194808  0.689897
..        ...       ...       ...       ...       ...
595  1.487545  0.382326  1.182874 -0.633747  1.133755
596 -0.808363 -0.344621  0.044030 -1.815555 -1.024116
597 -0.449296 -0.356131 -0.016657 -1.755402 -0.655351
598 -1.810308 -0.208485 -1.208528  0.563684 -0.048098
599 -0.287509  0.954035 -1.269338 -0.751203  0.111065

[600 rows x 5 columns]


In [63]:
pca.explained_variance_ratio_

array([0.33946671, 0.20167488, 0.20084627, 0.1899972 , 0.06801495])

In [66]:
pca=PCA(n_components=2)
pca1=pca.fit_transform(x)


In [71]:
pca.explained_variance_ratio_

array([0.33946671, 0.20167488])

In [72]:
pca_x=pca1

In [75]:
from sklearn.model_selection import train_test_split
pca_train,pca_test,y_train,y_test=train_test_split(pca_x,y,test_size=0.2, random_state=42)

In [78]:
pca_test.shape

(120, 2)

In [79]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(pca_train,y_train)

LogisticRegression()

In [80]:
pred=lr.predict(pca_test)

In [81]:
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [83]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)

In [84]:
acc

0.7666666666666667

In [86]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(pca_train,y_train)

DecisionTreeClassifier()

In [88]:
dt_pred=dt.predict(pca_test)
dt_pred

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int8)

In [90]:
dt_acc=accuracy_score(y_test,dt_pred)

In [91]:
dt_acc

0.575

In [129]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=14)
rf.fit(pca_train,y_train)

RandomForestClassifier(n_estimators=14)

In [130]:
rf_pred=rf.predict(pca_test)
rf_pred

array([1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1], dtype=int8)

In [131]:
rf_acc=accuracy_score(y_test,rf_pred)
rf_acc

0.675

In [133]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(pca_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [134]:
knn_pred=knn.predict(pca_test)
knn_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int8)

In [135]:
knn_acc=accuracy_score(y_test,knn_pred)

In [136]:
knn_acc

0.7166666666666667

In [137]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(pca_train,y_train)

GaussianNB()

In [139]:
gnb_pred=gnb.predict(pca_test)
gnb_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [142]:
from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(pca_train,y_train)

BernoulliNB()

In [143]:
bnb_pred=bnb.predict(pca_test)

In [144]:
bnb_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [147]:
from sklearn.svm import SVC
sv=SVC(kernel="sigmoid")
sv.fit(pca_train,y_train)

SVC(kernel='sigmoid')

In [148]:
sv_pred=sv.predict(pca_test)

In [149]:
sv_pred

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int8)

In [153]:
svm1_acc=accuracy_score(y_test,sv_pred)
svm1_acc

0.55

In [154]:
from sklearn.svm import SVC
sv=SVC(kernel="linear")
sv.fit(pca_train,y_train)

SVC(kernel='linear')

In [155]:
sv_pred=sv.predict(pca_test)

In [156]:
sv_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [157]:
from sklearn.svm import SVC
sv=SVC(kernel="poly")
sv.fit(pca_train,y_train)

SVC(kernel='poly')

In [158]:
sv_pred=sv.predict(pca_test)

In [159]:
sv_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [160]:
from sklearn.svm import SVC
sv=SVC(kernel="rbf")
sv.fit(pca_train,y_train)

SVC()

In [161]:
sv_pred=sv.predict(pca_test)
sv_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)